### ISSUE TITLE
request for more details on the installation

### ISSUE THREAD

**Issue by glehmann** [cljoly/bepo.nvim#5]
I'm a long time bépo user, and I'd like to give neovim a try. Of course the default mapping is not usable with this keyboard layout so your project seems to be the way to go.

Unfortunately, as a pure neovim beginner, I have no idea how to install it.

Could you provide the beginners with a command line — a `git clone` I guess? — to install the plugin?

**Comment by cljoly** [comment]
Thanks for opening this issue @glehmann !

I’ve written some installation instructions in #6. Do they make sense? Could you please comment on the PR, pointing out anything that’s unclear?

Once you’ve reviewed that PR, I’ll merge it.

**Comment by cljoly** [comment]
I've merges that PR, feel free to reopen this issue if you would like to suggest improvements.
